name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create Tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: 'v'
          release_branches: master

      - name: Check if new tag is created
        id: check_tag
        run: |
          if [ -z "${{ steps.tag.outputs.new_tag }}" ] || [ "${{ steps.tag.outputs.new_tag }}" = "${{ steps.tag.outputs.previous_tag }}" ]; then
            echo "release_needed=false" >> $GITHUB_OUTPUT
          else
            echo "release_needed=true" >> $GITHUB_OUTPUT
          fi

      - name: Update & Commit CHANGELOG.md
        if: steps.check_tag.outputs.release_needed == 'true'
        run: |
          npx github-changelog-generator --token ${{ secrets.GITHUB_TOKEN }} --future-release ${{ steps.tag.outputs.new_tag }}
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "docs: update changelog for ${{ steps.tag.outputs.new_tag }}" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        if: steps.check_tag.outputs.release_needed == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          name: Release ${{ steps.tag.outputs.new_tag }}
          body: ${{ steps.tag.outputs.changelog }}
          files: |
            ezrelease.tcl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
